### PR TITLE
loop find method

### PR DESCRIPTION
**Pull request by difcareer**
loop find method, usefull for invoke parent's method

### CODE REVIEW

**Comment by difcareer** [comment]
code was formatted by my intellij, only a little change

**Comment by rovo89** [comment]
That's why I always use `git status` and `git diff` to review every single line that I'm going to commit. ;)

What did you change then? Can you please clean up your commit so that it includes only the real change and also show how you would use it?

I'm a bit confused what kind of loop you mean, as findMethodBestMatch (used by the callMethod helper) already uses a loop to check parent classes.

**Comment by difcareer** [comment]
"findMethodBestMatch (used by the callMethod helper) already uses a loop to check parent classes" this is what i want , I review this helpers code and find it which i wasn't found before,thanks! ignore my commit request,:)

**Comment by difcareer** [comment]
by the way,which ide you use? i use intellij,compile xposedBridge project and get many errors.

**Comment by rovo89** [comment]
I'm using Eclipse. You probably need to add the references manually that Eclipse stores in https://github.com/rovo89/XposedBridge/blob/master/.classpath

**Pull request closed without merging**
