### PR TITLE
Thread safety:  The settings file could be considered loaded before the map is available

### PR DESCRIPTION
**Pull request by ghost**
The scenario [that actually occurred in my code]:
1)  I call prefs.reload();
2)  mLoaded is set to false, and a thread (THREAD_2) is started to start loading the prefs file.
3)  I call prefs.getBoolean("pref_name", false); //the actual value of "pref_name" in the settings file is true.
4)  getBoolean calls awaitLoadedLocked(), which spins waiting for mLoaded to be true before it accesses the mMap.
5)  THREAD_2 dutifully loads the prefs file, but sets mLoaded to true just slightly before  mMap is available.
6)  Since mLoaded is true, awaitLoadedLocked() finishes and getBoolean accesses mMap.   Of course it doesn't find the key and returns the default value
7)  THREAD_2 sets mMap to the map containing the file contents.

The fix is simple:  Don't set mLoaded to true until after mMap has been set.

### CODE REVIEW

**Comment by rovo89** [comment]
Have you considered the `synchronized` attributes? `loadFromDiskLocked` is executed with a lock held. So when `mLoaded` is set to true, the other thread is either blocked from executing the synchronized block in `getBoolean` (in case the reload started first), or it has handed off control with the `wait()` statement, which it won't get back until `notifyAll()` has been called and the reload synchronized block has ended.

**Comment by ghost** [comment]
You're right, of course.  I missed the synchronized wrapped around the loadFromDiskLocked() method.  After I made the local change it appeared to fix the problem, but I think it was just happenstance becuse it's happening again.

I'll retract the PR and close the issue.

The issue still remains:  Occasionally (1 of 100 times) where a prefs.reload results in an empty map.  

It's hard to debug, but I think it's due to the prefs file being locked.  Perhaps I'm just hitting a timing issue where my settings app is writing a value through SharedPreferences while XSharedPreferences is trying a reload.  

In any case, I'll keep digging and be more judicious with my issue reports  :)

Thanks,
Ryan

**Comment by theknut** [comment]
Have you tried to commit your preferences edit instead of applying the
changes? I had that problem because apply writes the changes in background
while commit will write in the main thread. So occasionally I'd read the
old value instead of the new one. Changing from apply to commit solved it
for me.
Am 06.09.2014 17:21 schrieb "cryptyk" notifications@github.com:

**Comment by ghost** [comment]
I'm using commit now.  The problem isn't that it's reading the old value.  It's reading the default value because the settings map is empty.
I was writing to the settings file a LOT to keep track of some status in the app.  I've now moved those rapid writes into a different file so the cross-process contention should be drastically reduced.  I'll update as I test.

**Pull request closed without merging**
