### PR TITLE
Fix isThemeable position in ResourcesKey constructor.

### PR DESCRIPTION
**Pull request by androidrbox**
CM11 left isThemeable where it was and put the IBinder at the end.

### CODE REVIEW

**Comment by rovo89** [comment]
Cool, I didn't even know if any ROMs use this parameter, so thanks for the fast feedback. Just need to check if the ResourcesManager.getTopLevelResources() also has an additional parameter.

**Comment by rovo89** [comment]
Doesn't seem so: https://github.com/CyanogenMod/android_frameworks_base/blob/cm-11.0/core/java/android/app/ResourcesManager.java
So I'll leave out the additional boolean parameter for the findAndHookMethod of getTopLevelResources for now.

I'm currently preparing some release notes for a beta release. Could you check http://forum.xda-developers.com/showthread.php?t=1574401 in an hour or so to test it on CM11 (assuming you have it running)?

**Comment by androidrbox** [comment]
I manually updated my app_process with the one you commited and the XposedBridge I compiled with this patch, and I'm able to replace the bluetooth icon in my statusbar.

**Comment by rovo89** [comment]
Thanks, that sounds good.

**Comment by rovo89** [comment]
If you'd like to test the official beta version: http://forum.xda-developers.com/showpost.php?p=47771876&postcount=5621

**Comment by androidrbox** [comment]
Thanks.  Looks like it works great.

**Pull request merged**
