### PR TITLE
Make gradlew executable

### PR DESCRIPTION
**Pull request by pR0Ps**
Give gradlew executable permissions

### CODE REVIEW

**Comment by rovo89** [comment]
Thanks. Is it still OK to execute `gradle app:assembleRelease` or should I switch to `./gradlew app:assembleRelease` instead? The latter seems to be a bit slower...

**Comment by pR0Ps** [comment]
Running `gradle app:assembleRelease` should use the system gradle whereas `./gradlew app:assembleRelease` should use the gradle distribution specified in the `gradle/gradle-wrapper.properties` file.

**Comment by rovo89** [comment]
Right, I just verified this. I'm new to Gradle and thought that the wrapper was more or less a fallback in case you have no system gradle or the wrong version. I thought that the system gradle would respect the properties and would use the version defined there. But my tests showed that it's not the case.

It's also not clear to me when to switch to new versions of Gradle, the build tools etc. I would expect that latter is always (well, usually) better, but for some reason Android Studio created the project with Gradle 2.8. Would there be any reason not to switch to Gradle 2.10? Thanks for your assistence.

**Comment by pR0Ps** [comment]
I'm not sure about that. Honestly, I just upgrade when Android Studio tells me to and don't really think about it.

**Comment by kristomatos** [comment]
Android Studio tell me when to upgrade

**Comment by kristomatos** [comment]
#

**Pull request closed without merging**
