### PR TITLE
New method for field searching by type: findFieldsByExactType

### PR DESCRIPTION
**Pull request by BurgerZ**

### CODE REVIEW

**Comment by rovo89** [comment]
I remember you have suggested this via mail a month ago, however you didn't answer my questions (sent on the same day). I'll just copy my questions here:

Could you please tell me a real-life example where this would be useful?
I could kind of understand that the helper for methods can be helpful for ProGuard-protected
apps because there might be just one method with that specific signature and return type.
But looking for all booleans in a class? Can you really be confident that you will pick the right one?

For the implementation itself:
I have actually dropped the FieldUtils, but the type.isAssignableFrom() doesn't belong there anyway
(String can be assigned to Object, but the method name says it looks for exact matches). Also it's
not necessary after the type != field.getType() check. I'm not sure if type=null should be allowed.
I don't think so and it would crash anyway with this version. Finally, findField() is recursive because
at least for instance fields, it's safe to set or get the value even if the field has been declared in
a superclass. That only applies to one instances, whereas a hooked method from a superclass will affect
all subclasses.

**Comment by BurgerZ** [comment]
@rovo89 sorry, so much mails...(
Yes. I have proguarded class and I know that it has only one field of known type. But I don't know that variable's name, so this method helps to find such fields.
Class<?> launcher = Class.forName("com.miui.home.launcher.Launcher", false, mClassLoader);
Class<?> deleteZone = Class.forName("com.miui.home.launcher.DeleteZone", false, mClassLoader);
Field[] fields = XposedHelpers.findFieldsByExactType(launcher, deleteZone);
If you have better implementation - you can add your own method. 
I think it's very helpful.

**Comment by rovo89** [comment]
How about this?

``` java

    /**
     * Returns the first field of the given type in a class.
     * Might be useful for Proguard'ed classes to identify fields with unique types.
     * If no matching field was not found, a {@link NoSuchFieldError} will be thrown.
     */
    public static Field findFirstFieldByExactType(Class<?> clazz, Class<?> type) {
        Class<?> clz = clazz;
        do {
            for (Field field : clz.getDeclaredFields()) {
                if (field.getType() == type) {
                    field.setAccessible(true);
                    return field;
                }
            }
        } while ((clz = clz.getSuperclass()) != null);

        throw new NoSuchFieldError("Field of type " + type.getName() + " in class " + clazz.getName());
    }
```

It's untested, but I think it should work. I decided not to return an array because apart from laziness, I see no reason why you would want to use this if you don't know the field name to identify it.

**Comment by BurgerZ** [comment]
It works, but if we have two or more fields of given type and we want to find the second one (in case we know it's value)?
Example:

``` java
//the code from our unknown class
private String s1 = "ONE";
private String s2 = "TWO";
```

``` java
for (Field f : findFieldsByExactType(clazz, String.class)) {
    if (((String)f.get(clazz)).equals("TWO")) {
        //do whatever we want with this field
    }
}
```

**Comment by rovo89** [comment]
Sorry, but what's the real life use-case for this? I don't think Xposed needs to offer helpers for every little niche case.

**Comment by BurgerZ** [comment]
Ok. That's your point and I understand it. This can be done in module helper as well.

**Comment by kristomatos** [comment]
#

**Pull request closed without merging**
