### PR TITLE
Update Android plug-in and wrapper

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates the plug-in to `2.1.2` (latest version as of Jun 9, 2016)

### CODE REVIEW

**Comment by rovo89** [comment]
Did you find any information what has changed between 2.1.0 and 2.1.2? I didn't. I'm wondering if it's really necessary to update the project on every minor change. Maybe I should use more wildcards, even though the official recommendation is not to do that.

As for the Gradle wrapper: What's the reason you switched to the "all" package instead of the "bin" package?

**Comment by friederbluemle** [comment]
I am not sure about the exact plug-in changelog, but supposedly there were minor fixes and improvements regarding the compatibility with the latest Android Studio version. What is the downside of using the latest version? You are right that using wildcards is not recommended as it might lead to build instabilities.
Regarding the Gradle wrapper: Using `-all` makes it easier to write and debug Gradle scripts in the IDE. Android Studio's message: `You can configure Gradle wrapper to use distribution with sources. It will provide IDE with Gradle API/DSL documentation.` I can change it back if you like..

**Comment by rovo89** [comment]
> What is the downside of using the latest version?

Nothing bad with that itself. I also ask everyone to use the latest Xposed version. It's just that I'm very keen on keeping the version history clean, i.e. focused on the project content. If I wanted to keep up with the latest versions for everything, I would have to add a commit every few days/weeks, which from my point of view distracts from the real changes.

Anyway, I think I might use `2.1.+` as a compromise between always using the latest version and broken builds due to incompatible tool changes.

I'll also have a look at "bin" vs. "all" for the Gradle wrapper. Seems like I indeed used "all" in the past. The wrapper files were created by `gradle wrapper --gradle-version 2.13` if I remember correctly, afterwards I changed the line endings with `dos2unix gradlew.bat` (to prevent warnings during `git commit`) and removed the timestamp from `gradle-wrapper.properties` (as I felt that it doesn't matter when I executed the command).

**Comment by friederbluemle** [comment]
Okay sure, do you want me to remove the `2.1.2` commit? Or replace it with `2.1.+`?

Regarding gradle-wrapper.properties: Correct, if you use the Gradle provided `wrapper` task, it will generate a `-bin`. But for easier developement the use of `-all` might be better here (it will also fix the Android Studio warning). Regarding `gradlew.bat` - that file is only used on Windows platforms. As you know Windows uses CRLF as line separators, so `dos2unix` should not be used here. What is the Git warning you are seeing? And which version of Git?

**Pull request closed without merging**
