### PR TITLE
API to get path to Xposed error log.

### PR DESCRIPTION
**Pull request by pylerSM**

### CODE REVIEW

**Comment by rovo89** [comment]
I appreciate that you send so many pull requests. But you really need to provide use cases for new features, ideally in the commit message (so it's visible in the log later) or at least in the pull request itself. Also, just from looking at it, I can see that it introduces a syntax error. Xposed is used by 100,000s or even millions of users, anything going into the codebase must be checked very carefully in regard of code quality and style.

For this particular suggestion: Why do you need this? The log file is an internal implementation detail. Chances are that it will even go away completely in the future thanks to stricter SELinux.

**Comment by pylerSM** [comment]
I am thinking about "bugreport" feature in modules (attach xposed log file to email). But if it is not useful, close this.

**Comment by theknut** [comment]
You can't use the XposedBridge in Activities.
Am 30.10.2014 19:22 schrieb "pyler" notifications@github.com:

**Comment by pylerSM** [comment]
Well, you are right actually. So this is not right way.
Closed.

**Pull request closed without merging**
